src/core/urls.py
from django.conf.urls import url

from .views import (
    WordsAddView, WordsReviewView, WordsEditView, WordsApproveView,
    StudentsAddView,SuccessView, HomeView
)


app_name = 'core'

urlpatterns = [
    url(r'^review/', WordsReviewView.as_view(), name='words_review'),
    url(r'^words/success', SuccessView.as_view(), name='words_success'),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^words/add/$', WordsAddView.as_view(), name='words_add'),
    url(r'^words/(?P<pk>[0-9]+)/edit/$', WordsEditView.as_view(),
        name='words_edit'),
    url(r'^words/(?P<pk>[0-9]+)/approve/$', WordsApproveView.as_view(),
        name='words_approve'),
]

urlpatterns += [
    url(r'^students/add/$', StudentsAddView.as_view(), name='students_add'),
]

src/padakosham/urls.py
from django.contrib import admin

from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"data/", include('institutions.urls')),
    url(r'^', include('public_pages.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^ui_test/', include('ui_test.urls')),
    url(r'^dashboard/', include('core.urls')),
]

urlpatterns += [
    url(r'^home/', include('core.urls', namespace='home')),
]

src/ui_test/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^unlogin', views.login, name='unlogin'),
    url(r'^unsignup', views.signup, name='unsignup'),
    url(r'^unadd_student', views.add_student, name='unadd_student'),
    url(r'^unhome', views.home, name='home'),
]

src/ui_test/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

src/ui_test/views.py
from django.shortcuts import render

def login(request):
    return render(request, "apps/UI_test/login.html", )

def signup(request):
    return render(request, "apps/UI_test/signup.html", )

def add_student(request):
    return render(request, "apps/UI_test/student_registration.html", )

def home(request):
    return render(request, "apps/UI_test/home.html", )

src/templates/apps/UI_test/home.html
{% include "common/inner_pages.html" %}
<div class="wrapper">
  <div class="row">
    <div class="column col-lg-12 col-md-12 col-sm-12 col-xs-12" id="main">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-12">
              <div class="intro-message text-center">
                <a href="{% url 'home:students_add' %}"><button type="submit" class="btn btn-primary btn-lg white">Add New Student</button></a>
              </div>
            </div>
          </div>
      </div>
    </div>
    <div class="column col-lg-3 col-md-3 col-sm-3 col-xs-12 hidden" id="sidebar">
      {% include "common/sidebar.html" %}
    </div>
  </div>
</div>

src/templates/apps/UI_test/login.html
{% extends "common/layout.html" %}
{% block wrapper %}
<div class="intro-header">
  <div class="container">
    <div class="row vh100">
      <div class="col-lg-4 col-lg-offset-4">
        <div class="intro-message animated zoomIn">
          <h2>Padakosham</h2>
          <h4>Enter Your Details</h4>
          <form>
            <div class="form-group">
              <input type="text" class="form-control" id="username" placeholder="Username">
            </div>
            <div class="form-group">
              <input type="password" class="form-control" id="password" placeholder="Password">
            </div>
            <a href="#">
              <button type="submit" class="btn btn-success white pull-right">Sign In</button>
            </a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

src/templates/apps/UI_test/result.html
{% include "common/inner_pages.html" %}
<div class="wrapper">
  <div class="row">
    <div class="column col-lg-9 col-md-9 col-sm-9 col-xs-12" id="main">
      <div class="center">
		<div class="hmain">
			<h1 class="hcs" >31</h1>
			<h2>words!</h2>
		</div>
		<p class="p">Congratulations $Current_Student_Name you contributed to the project by adding 31 words!</p>
	</div>
    </div>
    <div class="column col-lg-3 col-md-3 col-sm-3 col-xs-12" id="sidebar">
      {% include "common/sidebar.html" %}
    </div>
  </div>
</div>

src/templates/apps/UI_test/signup.html
{% include "common/layout.html" %}
{% block wrapper %}
<div class="intro-header">
  <div class="container">
    <div class="row vh100">
      <div class="col-lg-4 col-lg-offset-4">
        <div class="intro-message animated zoomIn">
          <h2>Padakosham</h2>
          <h4>Enter Your Details</h4>
          <form>
            <div class="form-group animated bounceInLeft">
              <input type="text" class="form-control" id="user_name" placeholder="Username">
            </div>
            <div class="form-group animated bounceInRight">
              <input type="password" class="form-control" id="password" placeholder="Password">
            </div>
            <div class="form-group animated bounceInLeft">
              <input type="text" class="form-control" id="district" placeholder="District">
            </div>
            <div class="form-group animated bounceInRight">
              <input type="text" class="form-control" id="sub_district" placeholder="Sub-District">
            </div>
            <a href="#">
              <button type="submit" class="btn btn-success white pull-right">Register</button>
            </a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

src/templates/apps/UI_test/student_registration.html
{% include "common/inner_pages.html" %}
<div class="wrapper">
  <div class="row">
    <div class="column col-lg-9 col-md-9 col-sm-9 col-xs-12" id="main">
        <div class="container-fluid">
          <div class="row-fluid">
            <div class="col-lg-12 top-pad100">
              <h2 class="animated zoomIn white">Padakosham</h2>
              <h4 class="white">Enter Your Details</h4>
              <form>
                <div class="form-group animated bounceInLeft">
                  <input type="text" class="form-control" id="student_name" placeholder="Name">
                </div>
                <div class="form-group animated bounceInRight">
                  <input type="text" class="form-control" id="grade" placeholder="Grade">
                </div>
                <div class="form-group animated bounceInLeft">
                  <select class="form-control" id="district" onchange="loadData('subdistrict','/data/retrieve?district='+this.value, 'Sub-District')">
                    <option value="" disabled selected>District</option>
                  </select>
                </div>
                <div class="form-group animated bounceInRight">
                  <select class="form-control" id="subdistrict" onchange="loadData('school','/data/retrieve?subdistrict='+this.value, 'School')">
                    <option value="" disabled selected>Sub-District</option>
                  </select>
                </div>
                <div class="form-group animated bounceInLeft">
                  <select class="form-control" id="school">
                    <option value="" disabled selected>School</option>
                  </select>
                </div>
                <a href="#">
                  <button type="submit" class="btn btn-success white pull-right">Register</button>
                </a>
              </form>
            </div>
          </div>
      </div>
    </div>
    <div class="column col-lg-3 col-md-3 col-sm-3 col-xs-12" id="sidebar">
      {% include "common/sidebar.html" %}
    </div>
  </div>
</div>

<script type="text/javascript">

$(function(){
  loadData('district', '/data/retrieve?', 'District');
});

function loadData(id, url , option) {
    $("#"+id).html($('<option>', { 
        value   : option,
        text    : option,
        disabled: true,
        selected: true
    }));
    $.ajax({
      type: "GET",
      crossDomain: true,
      url: url,
      dataType: "json",
      success: function(resultData){
          $.each(resultData[Object.keys(resultData)[0]], function (i, item) {
              $("#"+id).append($('<option>', { 
                  value: item,
                  text : item 
              }));
          });
      },
      error: function(e) {
        alert('Check the Console to see Error Messages');
        console.log(e);
      },
    });
};

</script>