src/core/urls.py
from django.conf.urls import url

from .views import (
    WordsAddView, WordsReviewView, WordsEditView, WordsApproveView,
    StudentsAddView,SuccessView, HomeView
)


app_name = 'core'

urlpatterns = [
    url(r'^review/', WordsReviewView.as_view(), name='words_review'),
    url(r'^words/success', SuccessView.as_view(), name='words_success'),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^words/add/$', WordsAddView.as_view(), name='words_add'),
    url(r'^words/(?P<pk>[0-9]+)/edit/$', WordsEditView.as_view(),
        name='words_edit'),
    url(r'^words/(?P<pk>[0-9]+)/approve/$', WordsApproveView.as_view(),
        name='words_approve'),
]

urlpatterns += [
    url(r'^students/add/$', StudentsAddView.as_view(), name='students_add'),
]

src/padakosham/urls.py
from django.contrib import admin

from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"data/", include('institutions.urls')),
    url(r'^', include('public_pages.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^ui_test/', include('ui_test.urls')),
    url(r'^dashboard/', include('core.urls')),
]

urlpatterns += [
    url(r'^home/', include('core.urls', namespace='home')),
]

src/core/models.py
from django.db import models
from django.conf import settings

from utils.models import TimestampedBaseModel


User = settings.AUTH_USER_MODEL


class Category(models.Model):
    """
    Categories of words like adjective, noun, etc.
    """
    name = models.CharField(max_length=50)

    def __str__(self):
        return '%s' % self.name


class Language(models.Model):
    """
    The language code and its human readable form.
    """
    code = models.CharField(max_length=10)
    name = models.CharField(max_length=50)

    def __str__(self):
        return '%s' % self.name


class Place(models.Model):
    """
    Places info.
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return '%s' % self.name


class Word(TimestampedBaseModel):
    """
    Master table for the word text and related metadata.
    """
    text = models.CharField(max_length=50, verbose_name='വാക്ക്')
    etymology = models.TextField(null=True, blank=True,verbose_name='നിഷ്പത്തി')
    homonyms = models.ManyToManyField(
        'self',
        blank=True,
        related_name='homonyms',
        verbose_name='നാനാർത്ഥം'
    )
    is_dialect = models.BooleanField(default=False,verbose_name='പ്രാദേശികഭേദമാണോ?')
    origin_language = models.ForeignKey(Language, null=True, blank=True,related_name='originated_words',verbose_name='ഏതുഭാഷയിൽ നിന്നും വന്നു?')
    language = models.ForeignKey(Language, null=True, blank=True,verbose_name='ഭാഷ')
    place = models.ForeignKey(
        Place,
        null=True,
        blank=True,
        related_name="places",
        verbose_name='പ്രദേശം'
    )
    is_plural = models.BooleanField(default=False,verbose_name='ബഹുവചനമാണോ?')
    plural = models.OneToOneField(
        'self',
        null=True,
        blank=True,
        related_name='plural_of',
        verbose_name='ബഹുവചനം'
    )
    root = models.ForeignKey(
        'self', null=True, blank=True, related_name='derived_words', verbose_name='മൂലപദം')
    singular = models.OneToOneField(
        'self', null=True, blank=True, related_name='singular_of',verbose_name='ഏകവചനം')

    def __str__(self):
        return '%s' % self.text


class WordDetails(TimestampedBaseModel):
    """
    Contains info about Word entry and manipulation.
    """
    word = models.OneToOneField(Word)
    created_by = models.ForeignKey(User, related_name="words_created")
    is_verified = models.BooleanField(default=False)
    verified_by = models.ForeignKey(
        User,
        null=True,
        blank=True,
        related_name="words_verified"
    )
class Meaning(models.Model):
    MASCULINE = 'M'
    FEMININE = 'F'
    NEUTRAL = 'N'
    GENDER_CHOICES = (
        (MASCULINE, 'പുല്ലിംഗം',),
        (FEMININE,'സ്ത്രീലിംഗം ',),
        (NEUTRAL, 'നപുംസകലിംഗം',),
    )
    word = models.ForeignKey(Word)
    text = models.TextField(
        verbose_name='അർത്ഥം'
    )
    gender = models.CharField(
        max_length=1,
        choices=GENDER_CHOICES,
        default=NEUTRAL,
        verbose_name='ലിംഗം')
    category = models.ForeignKey(
        Category,
        null=True,
        blank=True,
        verbose_name='പദവിഭാഗം'
    )
    examples = models.TextField(null=True, blank=True,verbose_name='ഉദാഹരണം')
    synonyms = models.ManyToManyField(
        Word,
        blank=True,
        related_name="synonyms",
        verbose_name='പര്യായങ്ങൾ'
    )
    opposites = models.ManyToManyField(
        Word,
        blank=True,
        related_name='opposites',
        verbose_name='വിപരീതം'
    )
    # translation = models.ManyToManyField(
    #     'self',
    #     blank=True,
    #     related_name="translations",
    #     verbose_name='പരിഭാഷകൾ'
    # )

    def __str__(self):
        return '%s' % self.text

src/core/forms.py
from django import forms
from crispy_forms.helper import FormHelper

from .models import Word, Meaning


class WordAddForm(forms.ModelForm):

    homonyms = forms.CharField(
        required=False, 
        label='നാനാർത്ഥം'
    )
    place = forms.CharField(
        required=False, 
        label='പ്രദേശം'
    )
    plural = forms.CharField(
        required=False, 
        label='ബഹുവചനം'
    )
    singular = forms.CharField(
        required=False,
        label='ഏകവചനം'
    )
    root = forms.CharField(
        required=False,
        label='മൂലപദം'
    )

    
    class Meta:
    	model = Word
    	fields = [
        'text', 'etymology', 'origin_language']

    def __init__(self, *args, **kwargs):
        super(WordAddForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.fields['homonyms'].widget = forms.TextInput(
            attrs={'placeholder':'ഈ വാക്കിന്റെ വിവിധ അർത്ഥങ്ങൾ കോമ ഉപയോഗിച്ച് വേർതിരിച്ച്  ചേർക്കുക'}
        )
        self.fields['place'].widget = forms.TextInput(
            attrs={'placeholder':'ഈ വാക്ക് ഒരു പ്രാദേശികഭേദമാണെങ്കിൽ മാത്രം ഏതു പ്രദേശത്താണ്  പ്രചാരത്തിലുള്ളത് എന്ന് ചേർക്കുക'}
        )
        self.fields['plural'].widget = forms.TextInput(
            attrs={'placeholder':'ഈ വാക്കിന്റെ ബഹുവചനം എന്താണ്?'}
        )
        self.fields['singular'].widget = forms.TextInput(
            attrs={'placeholder':'ഈ വാക്കിന്റെ ഏകവചനം എന്താണ്?'}
        )
        self.fields['root'].widget = forms.TextInput(
            attrs={'placeholder':'ഈ വാക്കിന്റെ മൂലപദം എന്തെന്ന് കണ്ടെത്തി ചേർക്കുക'}
        )

class WordMeaningAddForm(forms.ModelForm):
    synonyms = forms.CharField(
        required=False, 
        label='പര്യായങ്ങൾ'
    )

    opposites = forms.CharField(
        required=False, 
        label='വിപരീതം'
    )

    class Meta:
        model = Meaning
        fields = [
            'text', 'gender', 'category',
            'examples',
        ]

    def __init__(self, *args, **kwargs):
        super(WordMeaningAddForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.fields['synonyms'].widget = forms.TextInput(
            attrs={'placeholder':'ഈ വാക്കിന്റെ വിവിധ പര്യായങ്ങൾ കോമ ഉപയോഗിച്ച് വേർതിരിച്ച്  ചേർക്കുക'}
        )
        self.fields['opposites'].widget = forms.TextInput(
            attrs={'placeholder':'ഈ ചേർക്കുന്ന അർത്ഥത്തിന്റെ വിപരീതാർത്ഥം വരുന്ന വാക്ക് ചേ‌‌ർക്കുക'}
        )

class StudentAddForm(forms.Form):
    name = forms.CharField(label='Your name', max_length=100)
    grade = forms.CharField(label='Your name', max_length=100)
    school =  forms.CharField(label='Your name', max_length=100)

src/core/views.py
import random

from django.views import View
from django.views.generic import FormView, TemplateView
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.forms import formset_factory

from cuser.models import CUser

from accounts.models import StudentProfile
from institutions.models import Institution

from .forms import WordAddForm, StudentAddForm, WordMeaningAddForm
from .models import Word, Place
from .words import get_word_objects

class HomeView(TemplateView):
    template_name = 'apps/UI_test/home.html'

class WordsReviewView(View):
    def get(self, request):
        unverified_words = Word.objects.filter(worddetails__is_verified=False)
        context = {
            'unverified_words': unverified_words
        }
        return render(request, "apps/core/review.html", context=context)

class SuccessView(View):
    def get(self, request):
        unverified_words = Word.objects.filter(worddetails__is_verified=False)
        context = {
            'unverified_words': unverified_words
        }
        return render(request, "apps/core/result.html", context=context)

class WordsEditView(View):
    def get(self, request, pk):
        return HttpResponse("LOL!")


class WordsApproveView(View):
    def post(self, request, pk):
        word = Word.objects.get(id=pk)
        word.worddetails.is_verified = True
        word.worddetails.verified_by = request.user
        word.worddetails.save()
        return redirect('review')


class StudentsAddView(FormView):
    template_name = 'apps/core/students_add.html'
    form_class = StudentAddForm

    def post(self, *args, **kwargs):
        name = self.request.POST.get('name')
        institution = Institution.objects.get(id=int(self.request.POST.get('school')))
        user = CUser()
        user.first_name = name
        user.email = name + str(random.randint(0, 100000)) + "@itschool.in"
        user.save()
        profile = StudentProfile()
        profile.institution = institution
        profile.grade = self.request.POST.get('grade')
        profile.user = user
        profile.user_id = user.id
        profile.save()
        self.request.session['student_id'] = user.id
        return redirect('/home/words/add/')


class WordsAddView(FormView):
    template_name = 'apps/core/words_add.html'
    form_class = WordAddForm
    form_set_class = WordMeaningAddForm

    def get_form_set(self):
        form_set_class = self.form_set_class
        kwargs = {}
        if self.request.method in ('POST', 'PUT'):
            kwargs.update({
                'data': self.request.POST,
                'files': self.request.FILES,
            })
        MeaningFormSet = formset_factory(
            form_set_class, extra=20,
            min_num=1, validate_min=True
        )
        return MeaningFormSet(**kwargs)

    def form_valid(self, form, form_set):
        word = form.save()

        homonyms_csv = form.cleaned_data['homonyms']
        if homonyms_csv:
            word.homonyms.add(*get_word_objects(homonyms_csv))

        place_name = form.cleaned_data['place']
        if place_name:
            place = Place(name=place_name)
            place.save()
            word.place = place

        plural_text = form.cleaned_data['plural']
        if plural_text:
            word.plural = get_word_objects(plural_text)[0]

        singular_text = form.cleaned_data['singular']
        if singular_text:
            word.plural = get_word_objects(singular_text)[0]

        root_text = form.cleaned_data['root']
        if root_text:
            word.plural = get_word_objects(root_text)[0]

        word.save()

        for f in form_set:
            meaning = f.save(commit=False)
            meaning.word = word
            meaning.save()

            synonyms_csv = f.cleaned_data.get('synonyms')
            if synonyms_csv:
                meaning.synonyms.add(*get_word_objects(synonyms_csv))

            opposites_csv = f.cleaned_data.get('opposites')
            if opposites_csv:
                meaning.opposites.add(*get_word_objects(opposites_csv))

            meaning.save()




        add_another = self.request.POST.get('add_another')
        finish = self.request.POST.get('finish')

        if finish:
            return redirect('/home/words/success/')
        else:
            return redirect('/home/words/add/')

    def form_invalid(self, form, form_set):
        return self.render_to_response(self.get_context_data(form=form))

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        form_set = self.get_form_set()
        if form.is_valid() and form_set.is_valid():
            return self.form_valid(form, form_set)
        else:
            return self.form_invalid(form, form_set)

    def get_context_data(self, *args, **kwargs):
        if 'form' not in kwargs:
            kwargs['form'] = self.get_form()
        if 'formset' not in kwargs:
            kwargs['formset'] = self.get_form_set()
        return super().get_context_data(*args, **kwargs)
        return context

src/templates/apps/core/result.html
{% include "common/inner_pages.html" %}
<div class="wrapper">
  <div class="row">
    <div class="column col-lg-12 col-md-12 col-sm-12 col-xs-12" id="main">
      <div class="center">
		<div class="hmain">
			<h1 class="hcs" >Thank you!</h1>
			<h2></h2>
		</div>
		<p class="p">വാക്കുകൾ ചേർത്ത് നിങ്ങൾ ഈ സംരംഭത്തിന്റെ ഭാഗമായിരിക്കുന്നു.</p><p class="p">  മലയാളം കമ്പ്യൂട്ടിങ്ങിനുള്ള നിങ്ങളുടെ സംഭാവനകൾ വിലമതിക്കാനാവാത്തതാണ്.</p>
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
      <br><br><br>
        <a class="btn btn-default btn-block" href="{% url 'home:home' %}">
          Go back to home
        </a>
      </div>
    </div>
	</div>
    </div>
    <div class="hidden column col-lg-3 col-md-3 col-sm-3 col-xs-12" id="sidebar">
      {% include "common/sidebar.html" %}
    </div>
  </div>
</div>

src/templates/apps/core/review.html
{% for word in unverified_words %}
    Word: {{ word.text }} <br>
    Meanings: <br>
    {% for meaning in word.meaning_set.all %}
      - {{ meaning.text }} <br>
    {% endfor %}
    <form action="{% url 'approve_word' pk=word.id %}" method="POST">{% csrf_token %} 
      <button type="submit" class="btn btn-success btn-lg white">Approve</button>
    </form>
    <a href="{% url 'edit_word' pk=word.id %}"><button type="submit" class="btn btn-success btn-lg white">Edit</button></a>
    <br> <br>
{% endfor %}

src/templates/apps/core/students_add.html
{% include "common/inner_pages.html" %}
<div class="wrapper">
  <div class="row">
    <div class="column col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="container">
          <div class="row-fluid">
            <div class="col-lg-12 top-pad100">
            <!-- Start form panel -->
            <!-- Form begin -->
            <div class="panel panel-default">
              <div class="panel-heading"><h2 class= "white">പദകോശം</h2></div>
                <div class="panel-body">
                  <form class="well" method='post' action="/home/students/add/">
                    <h4 class="white">നിങ്ങളുടെ വിവരങ്ങൾ ചേർക്കുക</h4>
                    {% csrf_token %}
                    <div class="form-group">
                      <input type="text" class="form-control" id="student_name" name="name" placeholder="പേര്" required='required'>
                    </div>
                    <div class="form-group">
                      <input type="text" class="form-control" id="grade" name="grade" placeholder="ക്ലാസ്" required='required'>
                    </div>
                    <div class="form-group">
                      <select class="form-control" id="district" onchange="loadData('subdistrict','/data/retrieve?district='+this.value, 'സബ്‌‌ജില്ല')">
                        <option value="" disabled selected>ജില്ല</option>
                      </select>
                    </div>
                    <div class="form-group">
                      <select class="form-control" id="subdistrict" onchange="loadData('school','/data/retrieve?subdistrict='+this.value, 'സ്കൂൾ')">
                        <option value="" disabled selected>സബ്‌‌ജില്ല</option>
                      </select>
                    </div>
                    <div class="form-group">
                      <select class="form-control" id="school" name="school">
                        <option value="" disabled selected>സ്കൂൾ</option>
                      </select>
                    </div>
                    <button type="submit" class="btn btn-success white pull-right">വാക്കുകൾ ചേർത്ത് തുടങ്ങുക </button>
                  </form>
                </div>
            </div>
            <!-- Form panel end -->
            <!-- Form end -->
            </div>
          </div>
      </div>
    </div>
    <div class="hidden column col-lg-3 col-md-3 col-sm-3 col-xs-12" id="sidebar">
      {% include "common/sidebar.html" %}
    </div>
  </div>
</div>

<script type="text/javascript">

$(function(){
  loadData('district', '/data/retrieve?', 'ജില്ല');
});

function loadData(id, url , option) {
    $("#"+id).html($('<option>', { 
        value   : option,
        text    : option,
        disabled: true,
        selected: true
    }));
    $.ajax({
      type: "GET",
      crossDomain: true,
      url: url,
      dataType: "json",
      success: function(resultData){
          $.each(resultData[Object.keys(resultData)[0]], function (i, item) {
              $("#"+id).append($('<option>', { 
                  value: item[0],
                  text : item[1] 
              }));
          });
      },
      error: function(e) {
        alert('Check the Console to see Error Messages');
        console.log(e);
      },
    });
};

</script>

src/templates/apps/core/words_add.html
{% load crispy_forms_tags %}

{% include "common/inner_pages.html" %}
<div class="wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="column col-lg-offset-2 col-lg-8">
        <form method='post' class="top-pad100 bottom-pad100">
          {% csrf_token %}
          <div class="panel panel-default">
            <div class="panel-heading">
            <h4>
              ഒരു പുതിയ വാക്ക് ചേർക്കാം
            </h4>
            </div>
            <div class="panel-body">
                <div class="tc-word-form">
                  {{ form.text|as_crispy_field }}
                  {{ form.etymology|as_crispy_field }}
                  {{ form.homonyms|as_crispy_field }}
                  {{ form.origin_language|as_crispy_field }}
                  {{ form.place|as_crispy_field }}
                  {{ form.plural|as_crispy_field }}
                  {{ form.singular|as_crispy_field }}
                  {{ form.root|as_crispy_field }}
                </div>                    
            </div>
          </div>
          <div class="tc-meaning-form-wrap">
            {{ formset.management_form }} 
            {% for form_meaning in formset %}
              <div class="panel panel-default tc-meaning-form
                        {% if forloop.counter != 1 %}
                          hidden
                        {% endif %}
              ">
                <div class="panel-heading">
                  <h6>Meaning {{ forloop.counter }}</h6>
                </div>
                <div class="panel-body">
                    {{ form_meaning.text|as_crispy_field }}
                    {{ form_meaning.category|as_crispy_field }}
                    {{ form_meaning.gender|as_crispy_field }}
                    {{ form_meaning.examples|as_crispy_field }}
                    {{ form_meaning.synonyms|as_crispy_field }}
                    {{ form_meaning.opposites|as_crispy_field }}
                </div>
              </div>
            {% endfor %}
          </div>
          <div class="tc-form-controls">
            <div class="row">
              <div class="col-md-4">
                <a class="btn btn-sm btn-default tc-btn-menaing-new" href='#'>Add another meaning</a>                            
              </div>
              <div class="col-md-8 text-right">
                <input class="btn btn-sm btn-success" type="submit" name="finish" value='വാക്കുകൾ എല്ലാം ചേർത്ത് കഴിഞ്ഞ് ഇവിടെ ക്ലിക്ക് ചെയ്യുക'>
                <input class="btn btn-sm btn-success" type="submit" name="add_another" value='മറ്റൊരു വാക്കു കൂടി ചേർക്കുക'>
              </div>
            </div>
            
          </div>
        </form>
      </div>
      <div class="hidden column col-lg-3 col-md-3 col-sm-3 col-xs-12" id="sidebar">
        {% include "common/sidebar.html" %}
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

$(function(){
  loadData('district', '/data/retrieve?', 'District');
  $('.tc-btn-menaing-new').click(function(event){
    event.preventDefault();
    var panel_meaning_new = $('.tc-meaning-form.hidden').first();
    panel_meaning_new.removeClass('hidden');

    $('html, body').animate({
        scrollTop: panel_meaning_new.offset().top - 80,
    }, 500);
    
  });
});

function loadData(id, url , option) {
    $("#"+id).html($('<option>', { 
        value   : option,
        text    : option,
        disabled: true,
        selected: true
    }));
    $.ajax({
      type: "GET",
      crossDomain: true,
      url: url,
      dataType: "json",
      success: function(resultData){
          $.each(resultData[Object.keys(resultData)[0]], function (i, item) {
              $("#"+id).append($('<option>', { 
                  value: item,
                  text : item 
              }));
          });
      },
      error: function(e) {
        alert('Check the Console to see Error Messages');
        console.log(e);
      },
    });
};

</script>